# Day 3 — Linear Algebra for ML

In [18]:
import numpy as np

## Step 1:

- The system will evaluate students' Architectural hand drafting performance.
- On a scale frome one to ten rate how much detail you put into the following features: shade, color, drafting, #sheets

In [28]:
drawing_features = np.array(
    [[8, 5, 6, 5],
     [4, 9, 7, 8],
     [2, 3, 10, 7]]
)

weights = np.array([7, 5, 9, 3])
print("Features matrix:\n", drawing_features)
print("Weights matrix:\n", weights)


Features matrix:
 [[ 8  5  6  5]
 [ 4  9  7  8]
 [ 2  3 10  7]]
Weights matrix:
 [7 5 9 3]


## Step 2:

In [29]:
by_hand_prediction = 8 * 7 + 5 * 5 + 6 * 9 + 5 * 3
print("Dot product of a sample vector and a weight vector(manual calculation):", by_hand_prediction)
prediction = np.dot(drawing_features[0], weights)
print("Dot product of a sample vector and a weight vector(using np.dot()):", prediction)

Dot product of a sample vector and a weight vector(manual calculation): 150
Dot product of a sample vector and a weight vector(using np.dot()): 150


The importance of  the dot product lays under the idea that a model takes the user data as features and utilises their specified weights to produce meaningful outputs based on solid mathematical concepts. It performs its operations on an atomic level.

## Step 3:

In [32]:
result = drawing_features @ weights
print("Predicted results for all samples:\n", result)

Prediction results for all samples:
 [150 160 140]


Matrix multiplication provides the same functionality of a dot product, but on larger scale. I t is a better device than using a normal loop.

## Step 4:

In [34]:
mtx1 = np.array(
    [[2,4],
     [8,6]]
)
mtx2 = np.array([[8,4,7,1]])

multipli = mtx1 @ mtx2

print(multipli)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 2)

- General rule: for A@B wher A is (m,n) and B is (q,r), to have a result of shape (m,r) q must be equal to r.
- The error is due to mtx1 having 2 columns and mtx2 having 1 row. (2x2),(1,4)
- How to fix it : adding a second row to mtx2 or removing the second column from mtx1.
- Either (2x2)x(2,4) or (2x1)x(1x4)

In [35]:
print("Matrix 1 dimensions:", mtx1.shape)
print("Matrix 2 dimensions:", mtx2.shape)

Matrix 1 dimensions: (2, 2)
Matrix 2 dimensions: (1, 4)


How to fix it:

In [36]:
mtx3 = np.array(
    [[2,4],
     [8,6]]
)
mtx4 = np.array([[8,4,7,1],
                [3,0,4,7]])
# Now mtx4 has 2 rows -- (2x2)x(2x4)
multipli = mtx3 @ mtx4

print(multipli)

[[28  8 30 30]
 [82 32 80 50]]
